spring.application.name=Ecom
spring.datasource.url=jdbc:mysql://localhost:3306/ecom
spring.datasource.username=root
spring.datasource.password=292929

spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivanshbisnoi@gmail.com
spring.mail.password=fmdh srxr mktc hrav
spring.mail.properties.mail.smtp.starttls.enable=true